### ISSUE TITLE
Start container as non-root user

### ISSUE THREAD

**Issue by soosap** [keymetrics/pm2-docker-alpine#21]
First of all, thanks for the image. Following best practices I learned that it's best to not start containers as a root user.

When I switch to the node user though, I get "permission denied" error:

```
Error: EACCES: permission denied, open '/usr/local/lib/node_modules/pm2/node_modules/array-unique/index.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/micromatch/lib/utils.js:13:16)
    at Module._compile (module.js:569:30)
```

Is there a way to start this container as non-root user, i.e. assuming user "node". When doing so, for what files and directories do I need to change ownership to that new user?

**Comment by simonepri** [comment]
@Unitech any thought on this?

**Comment by jvduf** [comment]
I ran into this problem as well. 

As a Linux n00b I discovered several issues with this:
1) `npm` has been installed by the `root` user in the original `node:alpine` image
2) installing `pm2` therefor is only possible using the `root` user as well
3) executing `pm2` as a different user is not possible because it has been installed as root, so it gives you "permission denied"

To run NPM and PM2 using a different user I've created my own image with the following tweaks:
```
RUN chown -R USER:GROUP $(npm config get prefix)/lib/node_modules
RUN chown -R USER:GROUP /usr/local/bin/pm2
```

**Comment by simonepri** [comment]
@Unitech maybe we can add the @jvduf workaround to the readme. What do you think about?

**Comment by jvduf** [comment]
I've been experimenting some more...

This might be a cleaner option and is also suggested solution as per https://docs.npmjs.com/getting-started/fixing-npm-permissions

```
RUN mkdir /home/USERNAME/.npm-global \
    && npm config set prefix '/home/USERNAME/.npm-global' \
    && export PATH=/home/USERNAME/.npm-global/bin:$PATH \
    && npm install -g pm2
```

**Comment by jvduf** [comment]
This is part of my Dockerfile:

```
RUN addgroup -g 9999 app && adduser -u 9999 -G app -D app -s /bin/bash \
    && apk upgrade --update \
    && apk add --no-cache \
       bash bash-completion \
       git

#    && npm install -g pm2
# RUN chown -R app:app $(npm config get prefix)/lib/node_modules
# RUN chown -R app:app $(which pm2)

COPY ./bash/.bash* /home/app/

USER app
ENV HOME=/home/app/
WORKDIR $HOME

RUN mkdir /home/app/.npm-global \
    && npm config set prefix '/home/app/.npm-global' \
    && export PATH=/home/app/.npm-global/bin:$PATH \
    && npm install -g pm2
```
